include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types: true
    - annotate_redeclares: true
    - cancel_subscriptions: true
    - close_sinks: true
    - combinators_ordering: true
    - comment_references: true
    - invalid_case_patterns: true
    - one_member_abstracts: true
    - only_throw_errors: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true